#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vsprojectrh
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VSPROJECTS")]
	public partial class VSPROJECTSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertloginn(loginn instance);
    partial void Updateloginn(loginn instance);
    partial void Deleteloginn(loginn instance);
    partial void InsertUserAdd(UserAdd instance);
    partial void UpdateUserAdd(UserAdd instance);
    partial void DeleteUserAdd(UserAdd instance);
    partial void InsertCampaignsTable(CampaignsTable instance);
    partial void UpdateCampaignsTable(CampaignsTable instance);
    partial void DeleteCampaignsTable(CampaignsTable instance);
    partial void InsertDonationNowShow(DonationNowShow instance);
    partial void UpdateDonationNowShow(DonationNowShow instance);
    partial void DeleteDonationNowShow(DonationNowShow instance);
    partial void InsertDonateNow(DonateNow instance);
    partial void UpdateDonateNow(DonateNow instance);
    partial void DeleteDonateNow(DonateNow instance);
    partial void Insertmsg(msg instance);
    partial void Updatemsg(msg instance);
    partial void Deletemsg(msg instance);
    partial void Insertcamp(camp instance);
    partial void Updatecamp(camp instance);
    partial void Deletecamp(camp instance);
    #endregion
		
		public VSPROJECTSDataContext() : 
				base(global::vsprojectrh.Properties.Settings.Default.VSPROJECTSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VSPROJECTSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VSPROJECTSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VSPROJECTSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VSPROJECTSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<loginn> loginns
		{
			get
			{
				return this.GetTable<loginn>();
			}
		}
		
		public System.Data.Linq.Table<UserAdd> UserAdds
		{
			get
			{
				return this.GetTable<UserAdd>();
			}
		}
		
		public System.Data.Linq.Table<CampaignsTable> CampaignsTables
		{
			get
			{
				return this.GetTable<CampaignsTable>();
			}
		}
		
		public System.Data.Linq.Table<DonationNowShow> DonationNowShows
		{
			get
			{
				return this.GetTable<DonationNowShow>();
			}
		}
		
		public System.Data.Linq.Table<DonateNow> DonateNows
		{
			get
			{
				return this.GetTable<DonateNow>();
			}
		}
		
		public System.Data.Linq.Table<msg> msgs
		{
			get
			{
				return this.GetTable<msg>();
			}
		}
		
		public System.Data.Linq.Table<camp> camps
		{
			get
			{
				return this.GetTable<camp>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loginn")]
	public partial class loginn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Email;
		
		private string _pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    #endregion
		
		public loginn()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserAdd")]
	public partial class UserAdd : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _namee;
		
		private long _phone;
		
		private string _city;
		
		private string _addresss;
		
		private string _Email;
		
		private string _pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameeChanging(string value);
    partial void OnnameeChanged();
    partial void OnphoneChanging(long value);
    partial void OnphoneChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnaddresssChanging(string value);
    partial void OnaddresssChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    #endregion
		
		public UserAdd()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namee", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string namee
		{
			get
			{
				return this._namee;
			}
			set
			{
				if ((this._namee != value))
				{
					this.OnnameeChanging(value);
					this.SendPropertyChanging();
					this._namee = value;
					this.SendPropertyChanged("namee");
					this.OnnameeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="BigInt NOT NULL")]
		public long phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addresss", DbType="VarChar(50)")]
		public string addresss
		{
			get
			{
				return this._addresss;
			}
			set
			{
				if ((this._addresss != value))
				{
					this.OnaddresssChanging(value);
					this.SendPropertyChanging();
					this._addresss = value;
					this.SendPropertyChanged("addresss");
					this.OnaddresssChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CampaignsTable")]
	public partial class CampaignsTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Data.Linq.Binary _ImageData;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnImageDataChanging(System.Data.Linq.Binary value);
    partial void OnImageDataChanged();
    #endregion
		
		public CampaignsTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageData", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ImageData
		{
			get
			{
				return this._ImageData;
			}
			set
			{
				if ((this._ImageData != value))
				{
					this.OnImageDataChanging(value);
					this.SendPropertyChanging();
					this._ImageData = value;
					this.SendPropertyChanged("ImageData");
					this.OnImageDataChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonationNowShow")]
	public partial class DonationNowShow : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Email;
		
		private int _RS;
		
		private int _Total_Donate;
		
		private string _crt;
		
		private System.Nullable<long> _Phone;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnRSChanging(int value);
    partial void OnRSChanged();
    partial void OnTotal_DonateChanging(int value);
    partial void OnTotal_DonateChanged();
    partial void OncrtChanging(string value);
    partial void OncrtChanged();
    partial void OnPhoneChanging(System.Nullable<long> value);
    partial void OnPhoneChanged();
    #endregion
		
		public DonationNowShow()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RS", DbType="Int NOT NULL")]
		public int RS
		{
			get
			{
				return this._RS;
			}
			set
			{
				if ((this._RS != value))
				{
					this.OnRSChanging(value);
					this.SendPropertyChanging();
					this._RS = value;
					this.SendPropertyChanged("RS");
					this.OnRSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Donate", DbType="Int NOT NULL")]
		public int Total_Donate
		{
			get
			{
				return this._Total_Donate;
			}
			set
			{
				if ((this._Total_Donate != value))
				{
					this.OnTotal_DonateChanging(value);
					this.SendPropertyChanging();
					this._Total_Donate = value;
					this.SendPropertyChanged("Total_Donate");
					this.OnTotal_DonateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt", DbType="NVarChar(50)")]
		public string crt
		{
			get
			{
				return this._crt;
			}
			set
			{
				if ((this._crt != value))
				{
					this.OncrtChanging(value);
					this.SendPropertyChanging();
					this._crt = value;
					this.SendPropertyChanged("crt");
					this.OncrtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="BigInt")]
		public System.Nullable<long> Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonateNow")]
	public partial class DonateNow : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Email;
		
		private string _crt;
		
		private long _RS;
		
		private System.Nullable<long> _total_donate;
		
		private System.Nullable<int> _ID;
		
		private System.Nullable<long> _Phone;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OncrtChanging(string value);
    partial void OncrtChanged();
    partial void OnRSChanging(long value);
    partial void OnRSChanged();
    partial void Ontotal_donateChanging(System.Nullable<long> value);
    partial void Ontotal_donateChanged();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnPhoneChanging(System.Nullable<long> value);
    partial void OnPhoneChanged();
    #endregion
		
		public DonateNow()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crt", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string crt
		{
			get
			{
				return this._crt;
			}
			set
			{
				if ((this._crt != value))
				{
					this.OncrtChanging(value);
					this.SendPropertyChanging();
					this._crt = value;
					this.SendPropertyChanged("crt");
					this.OncrtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RS", DbType="BigInt NOT NULL")]
		public long RS
		{
			get
			{
				return this._RS;
			}
			set
			{
				if ((this._RS != value))
				{
					this.OnRSChanging(value);
					this.SendPropertyChanging();
					this._RS = value;
					this.SendPropertyChanged("RS");
					this.OnRSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_donate", DbType="BigInt")]
		public System.Nullable<long> total_donate
		{
			get
			{
				return this._total_donate;
			}
			set
			{
				if ((this._total_donate != value))
				{
					this.Ontotal_donateChanging(value);
					this.SendPropertyChanging();
					this._total_donate = value;
					this.SendPropertyChanged("total_donate");
					this.Ontotal_donateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="BigInt")]
		public System.Nullable<long> Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.msg")]
	public partial class msg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _msg1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onmsg1Changing(string value);
    partial void Onmsg1Changed();
    #endregion
		
		public msg()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="msg", Storage="_msg1", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string msg1
		{
			get
			{
				return this._msg1;
			}
			set
			{
				if ((this._msg1 != value))
				{
					this.Onmsg1Changing(value);
					this.SendPropertyChanging();
					this._msg1 = value;
					this.SendPropertyChanged("msg1");
					this.Onmsg1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.camp")]
	public partial class camp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _details;
		
		private string _targets;
		
		private string _campaign_type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndetailsChanging(string value);
    partial void OndetailsChanged();
    partial void OntargetsChanging(string value);
    partial void OntargetsChanged();
    partial void Oncampaign_typeChanging(string value);
    partial void Oncampaign_typeChanged();
    #endregion
		
		public camp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_details", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string details
		{
			get
			{
				return this._details;
			}
			set
			{
				if ((this._details != value))
				{
					this.OndetailsChanging(value);
					this.SendPropertyChanging();
					this._details = value;
					this.SendPropertyChanged("details");
					this.OndetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_targets", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string targets
		{
			get
			{
				return this._targets;
			}
			set
			{
				if ((this._targets != value))
				{
					this.OntargetsChanging(value);
					this.SendPropertyChanging();
					this._targets = value;
					this.SendPropertyChanged("targets");
					this.OntargetsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_campaign_type", DbType="NVarChar(100)")]
		public string campaign_type
		{
			get
			{
				return this._campaign_type;
			}
			set
			{
				if ((this._campaign_type != value))
				{
					this.Oncampaign_typeChanging(value);
					this.SendPropertyChanging();
					this._campaign_type = value;
					this.SendPropertyChanged("campaign_type");
					this.Oncampaign_typeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
